version: '3.4'

services:
  medsyncwebapp:
    image: medsyncwebapp
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3344:3344
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
